// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRTs1v2A_5pVCYaR2PVrIO5PZYQqQ8eIw',
    appId: '1:973634869353:web:64a880d6552d8649a16af8',
    messagingSenderId: '973634869353',
    projectId: 'notes-app-thulasirmn',
    authDomain: 'notes-app-thulasirmn.firebaseapp.com',
    storageBucket: 'notes-app-thulasirmn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfaXvJkgGutKeTQaCwSGBsxyDoqXWzCxU',
    appId: '1:973634869353:android:15b112eedbce42e5a16af8',
    messagingSenderId: '973634869353',
    projectId: 'notes-app-thulasirmn',
    storageBucket: 'notes-app-thulasirmn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnF9AT8uuh-mvws393Abn7sB2vCXlVkXE',
    appId: '1:973634869353:ios:1a5fb83887413f69a16af8',
    messagingSenderId: '973634869353',
    projectId: 'notes-app-thulasirmn',
    storageBucket: 'notes-app-thulasirmn.appspot.com',
    iosClientId:
        '973634869353-1ogc3o0srjcpfs54b1lc0sgtutil2119.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnF9AT8uuh-mvws393Abn7sB2vCXlVkXE',
    appId: '1:973634869353:ios:1a5fb83887413f69a16af8',
    messagingSenderId: '973634869353',
    projectId: 'notes-app-thulasirmn',
    storageBucket: 'notes-app-thulasirmn.appspot.com',
    iosClientId:
        '973634869353-1ogc3o0srjcpfs54b1lc0sgtutil2119.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
